@UserControl_HostAddress = https://localhost:7080

GET {{UserControl_HostAddress}}/users
###

POST {{UserControl_HostAddress}}/users
Content-Type: application/json
{
  "Email": "newuser@example.com",
  "Name": "New User"
}

###
@UserID=2
PUT {{UserControl_HostAddress}}/users/{{UserID}}
Content-Type: application/json
{
  "Email": "devil@hell.com",
  "Name": "Devil"
}
###
DELETE {{UserControl_HostAddress}}/users/{{UserID}}

###

GET {{UserControl_HostAddress}}/roles
###

POST {{UserControl_HostAddress}}/roles
Content-Type: application/json
{
  "RoleName": "New Role"
}
###
@RoleID=2 
PUT {{UserControl_HostAddress}}/roles/{{RoleID}}
Content-Type: application/json
{
  "RoleName": "New Role2"
}
###

DELETE {{UserControl_HostAddress}}/roles/{{RoleID}}

###

GET {{UserControl_HostAddress}}/AppPages

###

POST {{UserControl_HostAddress}}/AppPages
Content-Type: application/json
{
  "PageName": "New App Page",
  "Path": "/new-app-page",
  "AppName": "icon-new"
}
###
@AppPageID=6
PUT {{UserControl_HostAddress}}/AppPages/{{AppPageID}}
Content-Type: application/json
{
  "PageName": "New App Page2",
  "Path": "/new-app-page2",
  "AppName": "icon-new2"
}
###

DELETE {{UserControl_HostAddress}}/AppPages/{{AppPageID}}

###

GET {{UserControl_HostAddress}}/Permissions

###

POST {{UserControl_HostAddress}}/Permissions
Content-type: application/json
{
  "PageId": 2,
  "RoleId": 1,
  "CanView": true,
  "CanEdit": true,
  "CanDelete": true
}
###

@PermID=2
PUT {{UserControl_HostAddress}}/Permissions/{{PermID}}
Content-type: application/json
{
  "PageId": 2,
  "RoleId": 1,
  "CanView": true,
  "CanEdit": false,
  "CanDelete": false
}
###

DELETE {{UserControl_HostAddress}}/Permissions/{{PermID}}

###

GET {{UserControl_HostAddress}}/userroles

###
@newuserdId=5
@newroleId=3
POST {{UserControl_HostAddress}}/userroles?UserId={{newuserdId}}&RoleId={{newroleId}}
###

@olduserdId=5
@oldroleId=3
PUT {{UserControl_HostAddress}}/userroles?UserId={{olduserdId}}&RoleID={{oldroleId}}
Content-type: application/json
{
  "UserId": 3,
  "RoleId": 3
}
###

@delUserID=3
@delRoleID=3
DELETE {{UserControl_HostAddress}}/userroles?UserId={{delUserID}}&RoleId={{delRoleID}}

###
